language: php
php:
  - '5.6'
  - '7.0'
services:
  - mysql
before_install:
  - cp .env.example .env
  - sed -i 's/DATABASE=homestead/DATABASE=testdb/' .env
  - sed -i 's/USERNAME=homestead/USERNAME=root/' .env
  - sed -i 's/PASSWORD=secret/PASSWORD=/' .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
install:
  # Install dev php dependencies
  - composer install --no-interaction --prefer-dist
script:
  # Ensure phpcs triggers a failing build
  - sh -c "vendor/bin/phpcs --config-set ignore_warnings_on_exit 1"
  # Ensure breaking PSR2 compliance fails in CI
  - sh -c "vendor/bin/phpcs --standard=PSR2 --ignore=app/Http/routes.php app"
  # Seed database
  - sh -c "php artisan migrate --seed"
  # Run tests
  - sh -c "vendor/bin/phpunit"
  # Re-run tests to make sure we didn't break something
  - sh -c "php artisan key:generate"
  - sh -c "vendor/bin/phpunit"
