language: php
php:
  - '5.6'
  - '7.0'
services:
  - mysql
before_install:
  - cp .env.example .env
  - sed -i 's/DATABASE=homestead/DATABASE=testdb/' .env
  - sed -i 's/USERNAME=homestead/USERNAME=root/' .env
  - sed -i 's/PASSWORD=secret/PASSWORD=/' .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
install:
  # Install dev php dependencies
  - composer install --no-interaction --prefer-dist
script:
  # Generate Key
  - sh -c "php artisan key:generate"
  # Run tests 
  - sh -c "vendor/bin/phpunit"
